export const PILLARS = [
 {id:"policy", n:"01", short:"Policy",
  title:"Where Data Centers Meet Policy",
  headline:"Texas Policy Does Not Start in January",
  homeHead:"Policy shapes the project environment.",
  homeBody:"The legislative and regulatory decisions being made today will shape the future of data center development tomorrow.",
  caps:["Government affairs","Legislative monitoring","Regulatory strategy","Grid and utility regulatory developments","Water policy","Economic development policy","Tax incentive strategies"],
  body:[
   "Most organizations watch legislation when bills are filed. The companies that gain a competitive advantage start much earlier.",
   "Long before the legislative session convenes, lawmakers, regulators, agency leaders, stakeholders and industry groups are shaping the policy conversations that ultimately determine how data center development will be regulated across Texas. Water usage, power demand, tax incentives, permitting, infrastructure investment and community impact have all become increasingly important topics in Austin.",
   "For developers, operators, investors, property owners and their counsel, understanding those conversations early can be the difference between reacting to policy and helping shape the environment in which projects operate.",
   "@The Texas Advantage comes from understanding not only what is happening in Austin, but why it is happening, who is driving the discussion and how decisions being made today may affect projects tomorrow.",
   "Through its GRIDS capability, Gray Reed and GRPR help clients monitor legislative developments, evaluate regulatory risk, understand emerging policy trends and engage with the decision makers shaping the future of Texas infrastructure."],
  focus:["Texas Legislature","Grid policy","Utility regulatory matters","Water regulation and conservation","Tax incentive programs","Economic development policy","Local government authority","Infrastructure regulation"],
  message:"The Texas Advantage means understanding policy before it becomes regulation."},
 {id:"infrastructure", n:"02", short:"Infrastructure",
  title:"Where Data Centers Meet Infrastructure",
  headline:"The Real Story of a Project Begins Below the Surface",
  homeHead:"A data center may start with a site. Success is determined by infrastructure.",
  homeBody:"Power availability, transmission capacity, interconnection requirements, water access, transportation networks and utility infrastructure increasingly dictate whether projects move forward on schedule and within budget.",
  caps:["Site selection","Power procurement","Grid interconnection","Water law","Utility infrastructure","Transmission planning","Construction and development support"],
  body:[
   "A data center may start with a property, but success is determined by infrastructure.",
   "Power availability. Water access. Transmission capacity. Interconnection requirements. Pipeline infrastructure. Transportation corridors. Site readiness.",
   "These issues increasingly determine whether a project can move from concept to operation on schedule. They also shape the agreements, capital commitments and development decisions that must be made long before construction begins.",
   "Texas offers significant opportunity for data center development, but it is not a uniform market. Conditions vary across regions, utilities, transmission systems, groundwater resources and local jurisdictions. A development strategy that works in one part of the state may not translate directly to another.",
   "@The Texas Advantage comes from understanding how power, water, land and infrastructure interact across the state's evolving development landscape.",
   "The GRIDS frameworks brings together real estate, energy, water, construction and development capabilities to help clients identify constraints early, coordinate critical workstreams and create a stronger path from site evaluation through operation."],
  focus:["Site selection and site control","Power procurement","Grid interconnection","Water availability and rights","Land acquisition and entitlements","Utility and pipeline infrastructure","Transmission planning","Infrastructure and construction agreements"],
  message:"The Texas Advantage means understanding the infrastructure realities beneath the map."},
 {id:"communities", n:"03", short:"Communities",
  title:"Where Data Centers Meet Communities",
  headline:"Community Acceptance Is Now Project Infrastructure",
  homeHead:"Community acceptance has become project infrastructure.",
  homeBody:"Local officials, community leaders, residents and stakeholders are more engaged than ever in conversations about water resources, power usage, economic development and quality of life.",
  caps:["Public affairs","Community engagement","Stakeholder strategy","Media relations","Issues management","Reputation protection","Local government outreach"],
  body:[
   "The conversation surrounding data centers has changed.",
   "Communities increasingly want to understand how projects will affect water supplies, electric infrastructure, local services, tax revenues, quality of life and long-term growth. Local stakeholders, elected officials, community leaders and residents are becoming engaged earlier in the development process.",
   "As a result, community engagement is no longer simply a communications exercise. It is a business and project-development strategy.",
   "Organizations that engage stakeholders proactively can build trust, create stronger partnerships and address concerns before they become barriers. Those that wait until opposition emerges may find themselves reacting to a narrative that others have already defined.",
   "@The Texas Advantage comes from understanding both the opportunities and concerns that shape local decision-making.",
   "Through the Government Relations & Public Relations division, the GRIDS team helps clients plan stakeholder engagement, communicate project value, monitor public sentiment and navigate community, media and reputation issues throughout the project lifecycle."],
  focus:["Stakeholder engagement","Public affairs","Community relations","Media strategy","Local government outreach","Issues management","Public sentiment monitoring","Reputation strategy"],
  message:"The Texas Advantage means building support before opposition develops."},
 {id:"opportunity", n:"04", short:"Opportunity",
  title:"Where Data Centers Meet Opportunity",
  headline:"The Fastest-Growing Markets Create the Biggest Decisions",
  homeHead:"Texas continues to attract investment across the data center ecosystem.",
  homeBody:"Developers, operators, infrastructure funds, private equity sponsors, landowners and hyperscalers are pursuing opportunities in one of the country's most active markets.",
  caps:["Mergers and acquisitions","Joint ventures","Investment structures","Economic development incentives","Tax planning","Development strategy","Capital deployment"],
  body:[
   "Texas continues to attract substantial investment across the data center ecosystem.",
   "Developers, investors, operators, private equity sponsors, infrastructure funds, landowners and technology companies are competing to participate in a major infrastructure buildout. The opportunity is significant, but so are the strategic choices surrounding where to invest, how to structure a project and when to move.",
   "The most valuable opportunities often emerge at the intersection of market demand, infrastructure availability, public policy, economic incentives, financing structures and strategic partnerships.",
   "Organizations that understand those connections can identify value that others overlook and evaluate opportunities with a more complete view of execution risk.",
   "@The Texas Advantage comes from recognizing opportunity before it becomes obvious.",
   "GRIDS helps clients evaluate transactions, development strategies, incentive programs, investment structures and growth opportunities through a coordinated lens that reflects the realities of the Texas market."],
  focus:["Economic development incentives","Tax strategies","Joint ventures","Investment structures","Mergers and acquisitions","Development partnerships","Capital deployment","Growth planning"],
  message:"The Texas Advantage means recognizing opportunity before competitors do."},
 {id:"relationships", n:"05", short:"Relationships",
  title:"Where Data Centers Meet Relationships",
  headline:"Texas Runs on Relationships",
  homeHead:"Every state has laws. Texas has relationships.",
  homeBody:"Projects move more efficiently when the right stakeholders are engaged early and often. Relationships across government, industry, infrastructure and economic development organizations help organizations better understand risks, opportunities and emerging trends.",
  caps:["Legislative relationships","Regulatory engagement","Economic development partnerships","Industry relationships","Utility relationships","Local stakeholder engagement","Strategic introductions"],
  body:[
   "Every state has laws. Texas has relationships.",
   "Projects move more effectively when the right people are engaged at the right time. Regulatory questions can be addressed earlier. Stakeholders can become partners. Community concerns can be surfaced before they escalate. Opportunities can emerge through conversations that do not begin with a formal process.",
   "Successful projects are often supported by trusted relationships across government, business, infrastructure and local communities. Those relationships are not created overnight. They are built through consistent engagement, credibility and a working knowledge of the institutions and industries driving growth across Texas.",
   "@The Texas Advantage comes from understanding the people behind the process.",
   "GRIDS connects clients with professionals who have spent their careers working throughout Texas and helping organizations navigate the environments where business, policy, infrastructure and development intersect."],
  focus:["Government relationships","Regulatory engagement","Economic development partnerships","Community leadership","Industry organizations","Infrastructure stakeholders","Utility relationships","Strategic introductions"],
  message:"Texas runs on relationships. Successful projects do too."},
 {id:"local-counsel", n:"06", short:"Local Counsel",
  title:"Where Data Centers Meet Local Counsel",
  headline:"National Reach. Texas Advantage.",
  homeHead:"National reach. Texas insight.",
  homeBody:"Many organizations entering Texas work with sophisticated national and international law firms. Yet Texas presents challenges that require Texas-specific knowledge.",
  caps:["Local counsel support","Regulatory matters","Government affairs","Water law","Infrastructure development","Public affairs","Dispute resolution"],
  body:[
   "Many organizations investing in Texas already work with sophisticated national or international counsel. Even experienced outside counsel can encounter issues that are distinct to Texas.",
   "The state's energy markets operate differently. Water issues can require specialized knowledge. Legislative and regulatory priorities continue to evolve. Communities and local stakeholders bring different concerns to project development. Texas courts and local procedures may create additional considerations when disputes arise.",
   "Success often depends on having advisers who understand both the broader transaction and the Texas-specific realities that affect it.",
   "@GRIDS serves as a collaborative Texas partner for law firms advising clients across the data center ecosystem. Our role is to add targeted Texas capabilities, strengthen the broader counsel team and help protect the client relationship.",
   "Whether the need involves a transaction, government affairs, infrastructure strategy, public affairs, development, regulatory issues or a dispute, the GRIDS team works with outside counsel to help clients navigate Texas more effectively."],
  focus:["Local counsel support","Texas regulatory matters","Government affairs","Water law","Energy and infrastructure","Public affairs","Development strategy","Dispute resolution"],
  message:"The Texas Advantage includes a trusted Texas partner who strengthens the client's existing counsel team."}
];

export const HOME_SECTIONS = ["overview","understanding","pillars","six","platform","counsel","experience","insights"];

/* Home-page lists. Edit copy here; layout stays in main.js. */
export const ENTERING = ["Texas politics","Texas power markets","Texas water challenges","Texas communities","Texas economic development systems","Texas regulatory environments","Texas business relationships"];

